### http://localhost:8080/
spring:
  datasource:
    url: jdbc:mysql://아이피:포트/db
    username: 아이디
    password: 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled :  true
  thymeleaf:
    prefix: classpath:/templates/     ## (**템플릿 시작 위치 참조)
    suffix: .html                     ## (**템플릿의 확장자 이름 참조)
    check-template-location: true     ## (**해당위치에 파일이 있는지 없는지 체크
    cache: false                      ## (**캐시를 남기지 않는다.)
